// frontend/src/components/deck/DeckReviewPage.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import {
  getCards,
  deleteCard,
  moveCard,
  getAvailableTargetDecks,
} from '../../utils/storage'

const props = defineProps<{
  deck: any
  onBack: () => void
}>()

const cards = ref<any[]>([])
const selectedCard = ref<any>(null)
const showMoveModal = ref(false)
const cardToMove = ref<any>(null)
const availableDecks = ref<any[]>([])
const selectedTargetDeck = ref('')

watch(() => props.deck, (deck) => {
  if (deck) loadCards()
}, { immediate: false })

function loadCards() {
  if (!props.deck) return
  cards.value = getCards(props.deck.id)
}

function speak(text: string, langCode: string) {
  if (!window.speechSynthesis) return
  const utterance = new SpeechSynthesisUtterance(text)
  utterance.lang = langCode
  const voices = window.speechSynthesis.getVoices()
  const preferredVoice = voices.find(v => v.lang.startsWith(langCode.split('-')[0]))
  if (preferredVoice) utterance.voice = preferredVoice
  window.speechSynthesis.cancel()
  window.speechSynthesis.speak(utterance)
}

function handleDelete(id: string) {
  deleteCard(id)
  loadCards()
  selectedCard.value = null
}

function handleMoveCard(card: any) {
  cardToMove.value = card
  availableDecks.value = getAvailableTargetDecks(card.id)
  showMoveModal.value = true
}

function handleMoveToDeck(targetDeckId: string) {
  if (!cardToMove.value) return
  const result = moveCard(cardToMove.value.id, targetDeckId)
  if (result.success) {
    showMoveModal.value = false
    cardToMove.value = null
    selectedTargetDeck.value = ''
    loadCards()
    selectedCard.value = null
  } else {
    alert(result.message)
  }
}

function toggleCard(card: any) {
  selectedCard.value = selectedCard.value?.id === card.id ? null : card
}
</script>

<template>
  <div class="deck-review-page">
    <div class="deck-review-header">
      <button class="back-btn" @click="props.onBack">
        ← Back to Decks
      </button>
      <h2>{{ deck.name }}</h2>
      <div class="deck-info">
        <span>{{ cards.length }} cards</span>
        <span v-if="deck.description"> • {{ deck.description }}</span>
      </div>
    </div>

    <div class="deck-cards-list">
      <div v-if="cards.length === 0" class="empty-deck">
        <p>No flashcards in this deck yet.</p>
        <p>Import some images to add cards to this deck!</p>
      </div>

      <div v-else class="card-grid">
        <div v-for="card in cards" :key="card.id" class="review-card">
          <div class="review-front">
            <h3>{{ card.original }}</h3>
            <p class="pinyin">{{ card.pinyin }}</p>
            <button class="action-pill show-details" @click="toggleCard(card)">
              {{ selectedCard?.id === card.id ? '👁️ Hide' : '👁️ Show Explanation' }}
            </button>
          </div>

          <div v-if="selectedCard?.id === card.id" class="review-back">
            <p><strong>Translation:</strong> {{ card.translation }}</p>
            <br />
            <p><strong>Context:</strong> {{ card.context }}</p>
            <br />
            <p><strong>Grammar:</strong> {{ card.grammar }}</p>
            <br />
            <p><strong>Example:</strong> {{ card.example }}</p>

            <div class="card-bottom-actions">
              <div class="audio-section">
                <button class="audio-btn" @click.stop="speak(card.original, 'zh-CN')" title="Listen to Chinese">
                  🔊 Chinese
                </button>
                <button
                  class="audio-btn"
                  @click.stop="speak(card.translation, card.targetLang === 'fr' ? 'fr-FR' : 'en-US')"
                  title="Listen to Translation"
                >
                  🔊 Translation
                </button>
              </div>
              <div class="actions-col">
                <button class="action-pill" @click.stop="handleMoveCard(card)" title="Move to another deck">
                  📁 Move
                </button>
                <button class="action-pill danger" @click.stop="handleDelete(card.id)" title="Delete card">
                  🗑️ Delete
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Move Card Modal -->
    <div v-if="showMoveModal && cardToMove" class="modal-overlay" @click="showMoveModal = false">
      <div class="modal-content" @click.stop>
        <h3>Move Card to Another Deck</h3>
        <p>Choose a deck to move this card to:</p>

        <div v-if="availableDecks.length === 0" class="no-decks-message">
          No other decks available in this profile.
        </div>
        <div v-else class="move-card-form">
          <div class="form-group">
            <label for="target-deck">Select Target Deck:</label>
            <select id="target-deck" v-model="selectedTargetDeck">
              <option value="">Select a deck...</option>
              <option v-for="d in availableDecks" :key="d.id" :value="d.id">
                {{ d.name }} ({{ d.cardCount || 0 }} cards)
              </option>
            </select>
          </div>

          <div class="modal-actions">
            <button class="cancel-btn" @click="showMoveModal = false; selectedTargetDeck = ''">
              Cancel
            </button>
            <button
              class="save-btn"
              @click="selectedTargetDeck && handleMoveToDeck(selectedTargetDeck)"
              :disabled="!selectedTargetDeck"
            >
              Move Card
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// frontend/src/components/DeckReviewPage.jsx
import React, { useState, useEffect } from 'react';
import { getCards, deleteCard, getDeckById, moveCard, getAvailableTargetDecks } from '../utils/storage';

const DeckReviewPage = ({ deck, onBack }) => {
  const [cards, setCards] = useState([]);
  const [selectedCard, setSelectedCard] = useState(null);
  const [showMoveModal, setShowMoveModal] = useState(false);
  const [cardToMove, setCardToMove] = useState(null);
  const [availableDecks, setAvailableDecks] = useState([]);
  const [selectedTargetDeck, setSelectedTargetDeck] = useState('');

  useEffect(() => {
    if (deck) {
      loadCards();
    }
  }, [deck]);

  const loadCards = () => {
    const deckCards = getCards(deck.id);
    setCards(deckCards);
  };

  const speak = (text, langCode) => {
    if (!window.speechSynthesis) return;

    const utterance = new SpeechSynthesisUtterance(text);
    utterance.lang = langCode;

    // Try to find a voice that matches the language
    const voices = window.speechSynthesis.getVoices();
    const preferredVoice = voices.find(voice => voice.lang.startsWith(langCode.split('-')[0]));
    if (preferredVoice) {
      utterance.voice = preferredVoice;
    }

    window.speechSynthesis.cancel();
    window.speechSynthesis.speak(utterance);
  };

  const handleDelete = (id) => {
    deleteCard(id);
    loadCards();
    setSelectedCard(null);
  };

  const handleMoveCard = (card) => {
    setCardToMove(card);
    const decks = getAvailableTargetDecks(card.id);
    setAvailableDecks(decks);
    setShowMoveModal(true);
  };

  const handleMoveToDeck = (targetDeckId) => {
    if (!cardToMove) return;

    const result = moveCard(cardToMove.id, targetDeckId);
    if (result.success) {
      setShowMoveModal(false);
      setCardToMove(null);
      setSelectedTargetDeck('');
      loadCards(); // Refresh the card list
      setSelectedCard(null);
    } else {
      alert(result.message);
    }
  };

  if (!deck) {
    return (
      <div className="deck-review-page">
        <p>No deck selected</p>
      </div>
    );
  }

  return (
    <div className="deck-review-page">
      <div className="deck-review-header">
        <button className="back-btn" onClick={onBack}>
          ← Back to Decks
        </button>
        <h2>{deck.name}</h2>
        <div className="deck-info">
          <span>{cards.length} cards</span>
          {deck.description && <span>• {deck.description}</span>}
        </div>
      </div>

      <div className="deck-cards-list">
        {cards.length === 0 ? (
          <div className="empty-deck">
            <p>No flashcards in this deck yet.</p>
            <p>Import some images to add cards to this deck!</p>
          </div>
        ) : (
          <div className="card-grid">
            {cards.map(card => (
              <div key={card.id} className="review-card">
                <div className="review-front">
                  <h3>{card.original}</h3>
                  <p className="pinyin">{card.pinyin}</p>
                  <button
                    className="action-pill show-details"
                    onClick={() => setSelectedCard(selectedCard?.id === card.id ? null : card)}
                  >
                    {selectedCard?.id === card.id ? '👁️ Hide' : '👁️ Show Explanation'}
                  </button>
                </div>

                {selectedCard?.id === card.id && (
                  <div className="review-back">
                    <p><strong>Translation:</strong> {card.translation}</p>
                    <br />
                    <p><strong>Context:</strong> {card.context}</p>
                    <br />
                    <p><strong>Grammar:</strong> {card.grammar}</p>
                    <br />
                    <p><strong>Example:</strong> {card.example}</p>

                    <div className="card-bottom-actions">
                      <div className="audio-section">
                        <button
                          className="audio-btn"
                          onClick={(e) => { e.stopPropagation(); speak(card.original, 'zh-CN'); }}
                          title="Listen to Chinese"
                        >
                          🔊 Chinese
                        </button>
                        <button
                          className="audio-btn"
                          onClick={(e) => { e.stopPropagation(); speak(card.translation, card.targetLang === 'fr' ? 'fr-FR' : 'en-US'); }}
                          title="Listen to Translation"
                        >
                          🔊 Translation
                        </button>
                      </div>
                      <div className="actions-col">
                        <button
                          className="action-pill"
                          onClick={(e) => { e.stopPropagation(); handleMoveCard(card); }}
                          title="Move to another deck"
                        >
                          📁 Move
                        </button>
                        <button
                          className="action-pill danger"
                          onClick={(e) => { e.stopPropagation(); handleDelete(card.id); }}
                          title="Delete card"
                        >
                          🗑️ Delete
                        </button>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
      {/* Move Card Modal */}
      {showMoveModal && cardToMove && (
        <div className="modal-overlay" onClick={() => setShowMoveModal(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <h3>Move Card to Another Deck</h3>
            <p>Choose a deck to move this card to:</p>

            {availableDecks.length === 0 ? (
              <div className="no-decks-message">
                No other decks available in this profile.
              </div>
            ) : (
              <div className="move-card-form">
                <div className="form-group">
                  <label htmlFor="target-deck">Select Target Deck:</label>
                  <select
                    id="target-deck"
                    value={selectedTargetDeck}
                    onChange={(e) => setSelectedTargetDeck(e.target.value)}
                  >
                    <option value="">Select a deck...</option>
                    {availableDecks.map(deck => (
                      <option key={deck.id} value={deck.id}>
                        {deck.name} ({deck.cardCount || 0} cards)
                      </option>
                    ))}
                  </select>
                </div>

                <div className="modal-actions">
                  <button
                    className="cancel-btn"
                    onClick={() => {
                      setShowMoveModal(false);
                      setSelectedTargetDeck('');
                    }}
                  >
                    Cancel
                  </button>
                  <button
                    className="save-btn"
                    onClick={() => {
                      if (selectedTargetDeck) {
                        handleMoveToDeck(selectedTargetDeck);
                      }
                    }}
                    disabled={!selectedTargetDeck}
                  >
                    Move Card
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default DeckReviewPage;
