// frontend/src/components/profile/ProfileManager.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import {
  getProfiles,
  createProfile,
  getProfileById,
  deleteProfile,
  getDecks,
  renameProfile,
  validateProfileName,
} from '../../utils/storage'
import RenameModal from '../modal/RenameModal.vue'

const props = defineProps<{
  currentProfile: any
  onProfileChange: (profile: any) => void
  onCreateProfile?: (profile: any) => void
}>()

const profiles = ref<any[]>([])
const showCreateModal = ref(false)
const newProfileName = ref('')
const newProfileDescription = ref('')
const newProfileLang = ref('en')
const showRenameModal = ref(false)

onMounted(() => {
  loadProfiles()
})

function loadProfiles() {
  const profileList = getProfiles()
  profiles.value = profileList

  if (!props.currentProfile && profileList.length > 0) {
    props.onProfileChange(profileList[0])
  }
}

function handleDeleteProfile() {
  if (!props.currentProfile) return
  const profileDecks = getDecks(props.currentProfile.id)
  if (profileDecks.length > 0) {
    alert('Cannot delete profile that contains decks. Please delete all decks first.')
    return
  }
  if (window.confirm(`Are you sure you want to delete the profile "${props.currentProfile.name}"?`)) {
    deleteProfile(props.currentProfile.id)
    loadProfiles()
    const remainingProfiles = getProfiles()
    props.onProfileChange(remainingProfiles.length > 0 ? remainingProfiles[0] : null)
  }
}

function handleCreateProfile() {
  if (!newProfileName.value.trim()) return
  const profile = createProfile(
    newProfileName.value.trim(),
    newProfileDescription.value.trim(),
    newProfileLang.value,
  )
  newProfileName.value = ''
  newProfileDescription.value = ''
  newProfileLang.value = 'en'
  showCreateModal.value = false
  loadProfiles()
  props.onProfileChange(profile)
  props.onCreateProfile?.(profile)
}

function handleProfileSelect(e: Event) {
  const id = (e.target as HTMLSelectElement).value
  const profile = getProfileById(id)
  if (profile) props.onProfileChange(profile)
}
</script>

<template>
  <div class="profile-manager">
    <div class="profile-selector">
      <label for="profile-select">Study Profile:</label>
      <select
        id="profile-select"
        :value="currentProfile?.id || ''"
        @change="handleProfileSelect"
      >
        <option value="">Select a profile...</option>
        <option v-for="profile in profiles" :key="profile.id" :value="profile.id">
          {{ profile.name }} ({{ getDecks(profile.id).length }} decks)
        </option>
      </select>

      <button class="create-profile-btn" @click="showCreateModal = true">
        + New Profile
      </button>

      <button
        v-if="currentProfile"
        class="rename-profile-btn"
        @click="showRenameModal = true"
        title="Rename profile"
      >
        ✏️ Rename
      </button>

      <button
        v-if="currentProfile"
        class="delete-profile-btn"
        @click="handleDeleteProfile"
        :disabled="getDecks(currentProfile.id).length > 0"
        :title="getDecks(currentProfile.id).length > 0 ? 'Cannot delete profile with decks' : 'Delete profile'"
      >
        🗑️ Delete Profile
      </button>
    </div>

    <!-- Create Profile Modal -->
    <div v-if="showCreateModal" class="modal-overlay" @click="showCreateModal = false">
      <div class="modal-content" @click.stop>
        <h3>Create New Profile</h3>

        <div class="form-group">
          <label for="profile-name">Profile Name *</label>
          <input
            id="profile-name"
            type="text"
            v-model="newProfileName"
            placeholder="e.g., HSK Level 1, Business Chinese"
            autofocus
          />
        </div>

        <div class="form-group">
          <label for="profile-description">Description</label>
          <textarea
            id="profile-description"
            v-model="newProfileDescription"
            placeholder="Optional description for this study profile"
            rows="3"
          />
        </div>

        <div class="form-group">
          <label for="profile-lang">Default Language</label>
          <select id="profile-lang" v-model="newProfileLang">
            <option value="en">English</option>
            <option value="fr">Français</option>
          </select>
        </div>

        <div class="modal-actions">
          <button class="cancel-btn" @click="showCreateModal = false">Cancel</button>
          <button
            class="create-btn"
            @click="handleCreateProfile"
            :disabled="!newProfileName.trim()"
          >
            Create Profile
          </button>
        </div>
      </div>
    </div>

    <!-- Current Profile Info -->
    <div v-if="currentProfile" class="current-profile-info">
      <h4>{{ currentProfile.name }}</h4>
      <p v-if="currentProfile.description" class="profile-description">
        {{ currentProfile.description }}
      </p>
      <small class="profile-meta">
        Created: {{ new Date(currentProfile.createdAt).toLocaleDateString() }}
        <template v-if="currentProfile.decks">
          • Decks: {{ currentProfile.decks.length }}
        </template>
      </small>
    </div>

    <!-- Rename Profile Modal -->
    <RenameModal
      v-if="currentProfile"
      :isOpen="showRenameModal"
      @close="showRenameModal = false"
      :onRename="async (newName: string) => {
        const result = renameProfile(currentProfile.id, newName)
        if (result.success) {
          loadProfiles()
          const updated = getProfileById(currentProfile.id)
          if (updated) props.onProfileChange(updated)
        }
        return result
      }"
      :currentName="currentProfile.name"
      :validateName="(name: string) => validateProfileName(name, currentProfile.id)"
      title="Rename Profile"
      itemType="Profile"
    />
  </div>
</template>

// frontend/src/components/ProfileManager.jsx
import React, { useState, useEffect } from 'react';
import { getProfiles, createProfile, getProfileById, deleteProfile, getDecks, renameProfile, validateProfileName } from '../utils/storage';
import RenameModal from './RenameModal';

const ProfileManager = ({
  currentProfile,
  onProfileChange,
  onCreateProfile
}) => {
  const [profiles, setProfiles] = useState([]);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [newProfileName, setNewProfileName] = useState('');
  const [newProfileDescription, setNewProfileDescription] = useState('');
  const [newProfileLang, setNewProfileLang] = useState('en');
  const [showRenameModal, setShowRenameModal] = useState(false);

  useEffect(() => {
    loadProfiles();
  }, []);

  const loadProfiles = () => {
    const profileList = getProfiles();
    setProfiles(profileList);

    // Auto-select first profile if none selected
    if (!currentProfile && profileList.length > 0) {
      onProfileChange(profileList[0]);
    }
  };

  const handleDeleteProfile = () => {
    if (!currentProfile) return;

    const profileDecks = getDecks(currentProfile.id);
    if (profileDecks.length > 0) {
      alert('Cannot delete profile that contains decks. Please delete all decks first.');
      return;
    }

    if (window.confirm(`Are you sure you want to delete the profile "${currentProfile.name}"? This action cannot be undone.`)) {
      deleteProfile(currentProfile.id);
      loadProfiles();

      // Select another profile if available
      const remainingProfiles = getProfiles();
      if (remainingProfiles.length > 0) {
        onProfileChange(remainingProfiles[0]);
      } else {
        onProfileChange(null);
      }
    }
  };

  const handleCreateProfile = () => {
    if (!newProfileName.trim()) return;

    const profile = createProfile(
      newProfileName.trim(),
      newProfileDescription.trim(),
      newProfileLang
    );

    setNewProfileName('');
    setNewProfileDescription('');
    setNewProfileLang('en');
    setShowCreateModal(false);

    loadProfiles();
    onProfileChange(profile);

    if (onCreateProfile) {
      onCreateProfile(profile);
    }
  };

  const handleProfileSelect = (profileId) => {
    const profile = getProfileById(profileId);
    if (profile) {
      onProfileChange(profile);
    }
  };

  return (
    <div className="profile-manager">
      <div className="profile-selector">
        <label htmlFor="profile-select">Study Profile:</label>
        <select
          id="profile-select"
          value={currentProfile?.id || ''}
          onChange={(e) => handleProfileSelect(e.target.value)}
        >
          <option value="">Select a profile...</option>
          {profiles.map(profile => {
            const profileDecks = getDecks(profile.id);
            return (
              <option key={profile.id} value={profile.id}>
                {profile.name} ({profileDecks.length} decks)
              </option>
            );
          })}
        </select>

        <button
          className="create-profile-btn"
          onClick={() => setShowCreateModal(true)}
        >
          + New Profile
        </button>

        {/* Rename Profile Button */}
        {currentProfile && (
          <button
            className="rename-profile-btn"
            onClick={() => setShowRenameModal(true)}
            title="Rename profile"
          >
            ✏️ Rename
          </button>
        )}

        {/* Delete Profile Button */}
        {currentProfile && (
          <button
            className="delete-profile-btn"
            onClick={handleDeleteProfile}
            disabled={getDecks(currentProfile.id).length > 0}
            title={getDecks(currentProfile.id).length > 0 ? "Cannot delete profile with decks" : "Delete profile"}
          >
            🗑️ Delete Profile
          </button>
        )}
      </div>

      {/* Create Profile Modal */}
      {showCreateModal && (
        <div className="modal-overlay" onClick={() => setShowCreateModal(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <h3>Create New Profile</h3>

            <div className="form-group">
              <label htmlFor="profile-name">Profile Name *</label>
              <input
                id="profile-name"
                type="text"
                value={newProfileName}
                onChange={(e) => setNewProfileName(e.target.value)}
                placeholder="e.g., HSK Level 1, Business Chinese"
                autoFocus
              />
            </div>

            <div className="form-group">
              <label htmlFor="profile-description">Description</label>
              <textarea
                id="profile-description"
                value={newProfileDescription}
                onChange={(e) => setNewProfileDescription(e.target.value)}
                placeholder="Optional description for this study profile"
                rows={3}
              />
            </div>

            <div className="form-group">
              <label htmlFor="profile-lang">Default Language</label>
              <select
                id="profile-lang"
                value={newProfileLang}
                onChange={(e) => setNewProfileLang(e.target.value)}
              >
                <option value="en">English</option>
                <option value="fr">Français</option>
              </select>
            </div>

            <div className="modal-actions">
              <button
                className="cancel-btn"
                onClick={() => setShowCreateModal(false)}
              >
                Cancel
              </button>
              <button
                className="create-btn"
                onClick={handleCreateProfile}
                disabled={!newProfileName.trim()}
              >
                Create Profile
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Current Profile Info */}
      {currentProfile && (
        <div className="current-profile-info">
          <h4>{currentProfile.name}</h4>
          {currentProfile.description && (
            <p className="profile-description">{currentProfile.description}</p>
          )}
          <small className="profile-meta">
            Created: {new Date(currentProfile.createdAt).toLocaleDateString()}
            {currentProfile.decks && (
              <> • Decks: {currentProfile.decks.length}</>
            )}
          </small>
        </div>
      )}

      {/* Rename Profile Modal */}
      {currentProfile && (
        <RenameModal
          isOpen={showRenameModal}
          onClose={() => setShowRenameModal(false)}
          onRename={(newName) => renameProfile(currentProfile.id, newName)}
          currentName={currentProfile.name}
          validateName={(name) => validateProfileName(name, currentProfile.id)}
          title="Rename Profile"
          itemType="Profile"
        />
      )}
    </div>
  );
};

export default ProfileManager;
