// frontend/src/components/CardFormModal.jsx
import React, { useState, useEffect } from 'react';
import { getProfiles, getDecks, saveCard, updateCard } from '../utils/storage';

function CardFormModal({ isOpen, onClose, card, profileId, deckId, onSaved }) {
  const isEditing = !!card;

  // ── Form state ────────────────────────────────────────────────────────

  const [original, setOriginal] = useState('');
  const [pinyin, setPinyin] = useState('');
  const [targetLang, setTargetLang] = useState('en');
  const [translation, setTranslation] = useState('');
  const [context, setContext] = useState('');
  const [grammar, setGrammar] = useState('');
  const [example, setExample] = useState('');
  const [difficulty, setDifficulty] = useState('new');

  // Create-mode selectors
  const [selProfileId, setSelProfileId] = useState(profileId || '');
  const [selDeckId, setSelDeckId] = useState(deckId || '');
  const [availableDecks, setAvailableDecks] = useState([]);

  // Validation
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);

  // ── Reset form when modal opens ─────────────────────────────────────

  useEffect(() => {
    if (!isOpen) return;
    if (card) {
      setOriginal(card.original || '');
      setPinyin(card.pinyin || '');
      setTargetLang(card.targetLang || 'en');
      setTranslation(card.translation || '');
      setContext(card.context || '');
      setGrammar(card.grammar || '');
      setExample(card.example || '');
      setDifficulty(card.difficulty || 'new');
      setSelProfileId('');
      setSelDeckId(deckId || '');
    } else {
      setOriginal('');
      setPinyin('');
      setTargetLang('en');
      setTranslation('');
      setContext('');
      setGrammar('');
      setExample('');
      setDifficulty('new');
      setSelProfileId(profileId || '');
      setSelDeckId(deckId || '');
    }
    setError('');
    setSaving(false);
  }, [isOpen, card, profileId, deckId]);

  // ── Load decks when profile changes ─────────────────────────────────

  useEffect(() => {
    if (selProfileId) {
      setAvailableDecks(getDecks(selProfileId));
      // Reset deck selection if current deck not in this profile
      const deckStillValid = getDecks(selProfileId).some(d => d.id === selDeckId);
      if (!deckStillValid && !deckId) setSelDeckId('');
    } else {
      setAvailableDecks([]);
    }
  }, [selProfileId]);

  // ── Submit ────────────────────────────────────────────────────────────

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');

    if (!isEditing && !selDeckId) {
      setError('Please select a profile and deck.');
      return;
    }
    if (!original.trim()) {
      setError('Original text (Chinese) is required.');
      return;
    }
    if (!translation.trim()) {
      setError('Translation is required.');
      return;
    }

    setSaving(true);
    try {
      const fields = {
        original: original.trim(),
        pinyin: pinyin.trim(),
        targetLang,
        translation: translation.trim(),
        context: context.trim(),
        grammar: grammar.trim(),
        example: example.trim(),
        difficulty,
      };

      if (isEditing) {
        updateCard(card.id, fields);
      } else {
        saveCard(fields, selDeckId);
      }

      if (onSaved) onSaved();
      onClose();
    } catch (err) {
      setError(err.message || 'Failed to save card.');
    } finally {
      setSaving(false);
    }
  };

  if (!isOpen) return null;

  // ── Profiles for create-mode selector ────────────────────────────────

  const allProfiles = getProfiles();

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content card-form-modal" onClick={(e) => e.stopPropagation()}>
        <h3>{isEditing ? '✏️ Edit Card' : '➕ New Card'}</h3>

        <form onSubmit={handleSubmit}>
          {/* Create-mode: profile + deck selectors */}
          {!isEditing && (
            <>
              <div className="form-group">
                <label>Profile</label>
                <select
                  value={selProfileId}
                  onChange={(e) => setSelProfileId(e.target.value)}
                  disabled={saving}
                >
                  <option value="">-- Select profile --</option>
                  {allProfiles.map((p) => (
                    <option key={p.id} value={p.id}>{p.name}</option>
                  ))}
                </select>
              </div>

              {selProfileId && (
                <div className="form-group">
                  <label>Deck</label>
                  <select
                    value={selDeckId}
                    onChange={(e) => setSelDeckId(e.target.value)}
                    disabled={saving}
                  >
                    <option value="">-- Select deck --</option>
                    {availableDecks.map((d) => (
                      <option key={d.id} value={d.id}>
                        {d.name} ({getDecks().find(p => p.id === d.id)?.cardCount || 0} cards)
                      </option>
                    ))}
                  </select>
                </div>
              )}
            </>
          )}

          {/* Card fields */}
          <div className="form-group">
            <label>Original (Chinese) *</label>
            <input
              type="text"
              value={original}
              onChange={(e) => setOriginal(e.target.value)}
              placeholder="你好世界"
              disabled={saving}
              autoFocus
            />
          </div>

          <div className="form-group">
            <label>Pinyin</label>
            <input
              type="text"
              value={pinyin}
              onChange={(e) => setPinyin(e.target.value)}
              placeholder="nǐ hǎo shì jiè"
              disabled={saving}
            />
          </div>

          <div className="form-row">
            <div className="form-group">
              <label>Language</label>
              <select
                value={targetLang}
                onChange={(e) => setTargetLang(e.target.value)}
                disabled={saving}
              >
                <option value="en">English</option>
                <option value="fr">Français</option>
              </select>
            </div>

            <div className="form-group">
              <label>Difficulty</label>
              <select
                value={difficulty}
                onChange={(e) => setDifficulty(e.target.value)}
                disabled={saving}
              >
                <option value="new">New</option>
                <option value="hard">Hard</option>
                <option value="good">Good</option>
                <option value="easy">Easy</option>
              </select>
            </div>
          </div>

          <div className="form-group">
            <label>Translation *</label>
            <input
              type="text"
              value={translation}
              onChange={(e) => setTranslation(e.target.value)}
              placeholder="Hello world"
              disabled={saving}
            />
          </div>

          <div className="form-group">
            <label>Context</label>
            <textarea
              value={context}
              onChange={(e) => setContext(e.target.value)}
              placeholder="Usage context..."
              rows={2}
              disabled={saving}
            />
          </div>

          <div className="form-group">
            <label>Grammar</label>
            <textarea
              value={grammar}
              onChange={(e) => setGrammar(e.target.value)}
              placeholder="Grammar notes..."
              rows={2}
              disabled={saving}
            />
          </div>

          <div className="form-group">
            <label>Example</label>
            <textarea
              value={example}
              onChange={(e) => setExample(e.target.value)}
              placeholder="Another example sentence..."
              rows={2}
              disabled={saving}
            />
          </div>

          {error && <div className="error-message">{error}</div>}

          <div className="modal-actions">
            <button
              type="button"
              className="cancel-btn"
              onClick={onClose}
              disabled={saving}
            >
              Cancel
            </button>
            <button
              type="submit"
              className="create-btn"
              disabled={saving}
            >
              {saving ? '💾 Saving...' : '💾 Save Card'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

export default CardFormModal;

// frontend/src/components/card/CardFormModal.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { getProfiles, getDecks, saveCard, updateCard } from '../../utils/storage'

const props = defineProps<{
  isOpen: boolean
  card?: any
  profileId?: string
  deckId?: string
  onSaved?: () => void
}>()

const emit = defineEmits<{
  close: []
}>()

// Form state
const original = ref('')
const pinyin = ref('')
const targetLang = ref('en')
const translation = ref('')
const context = ref('')
const grammar = ref('')
const example = ref('')
const difficulty = ref('new')

// Create-mode selectors
const selProfileId = ref(props.profileId || '')
const selDeckId = ref(props.deckId || '')
const availableDecks = ref<any[]>([])

// Validation
const error = ref('')
const saving = ref(false)

const isEditing = () => !!props.card

// Reset form when modal opens
watch(() => props.isOpen, (open) => {
  if (!open) return
  if (props.card) {
    original.value = props.card.original || ''
    pinyin.value = props.card.pinyin || ''
    targetLang.value = props.card.targetLang || 'en'
    translation.value = props.card.translation || ''
    context.value = props.card.context || ''
    grammar.value = props.card.grammar || ''
    example.value = props.card.example || ''
    difficulty.value = props.card.difficulty || 'new'
    selProfileId.value = ''
    selDeckId.value = props.deckId || ''
  } else {
    original.value = ''
    pinyin.value = ''
    targetLang.value = 'en'
    translation.value = ''
    context.value = ''
    grammar.value = ''
    example.value = ''
    difficulty.value = 'new'
    selProfileId.value = props.profileId || ''
    selDeckId.value = props.deckId || ''
  }
  error.value = ''
  saving.value = false
})

// Load decks when profile changes
watch(selProfileId, (pid) => {
  if (pid) {
    availableDecks.value = getDecks(pid)
    const stillValid = getDecks(pid).some(d => d.id === selDeckId.value)
    if (!stillValid && !props.deckId) selDeckId.value = ''
  } else {
    availableDecks.value = []
  }
})

function handleProfileSelect(e: Event) {
  const target = e.target as HTMLSelectElement
  selProfileId.value = target.value
}

async function handleSubmit(e: Event) {
  e.preventDefault()
  error.value = ''

  if (!isEditing() && !selDeckId.value) {
    error.value = 'Please select a profile and deck.'
    return
  }
  if (!original.value.trim()) {
    error.value = 'Original text (Chinese) is required.'
    return
  }
  if (!translation.value.trim()) {
    error.value = 'Translation is required.'
    return
  }

  saving.value = true
  try {
    const fields = {
      original: original.value.trim(),
      pinyin: pinyin.value.trim(),
      targetLang: targetLang.value,
      translation: translation.value.trim(),
      context: context.value.trim(),
      grammar: grammar.value.trim(),
      example: example.value.trim(),
      difficulty: difficulty.value,
    }

    if (isEditing()) {
      updateCard(props.card.id, fields)
    } else {
      saveCard(fields, selDeckId.value)
    }

    if (props.onSaved) props.onSaved()
    emit('close')
  } catch (err: any) {
    error.value = err.message || 'Failed to save card.'
  } finally {
    saving.value = false
  }
}

const allProfiles = getProfiles()
</script>

<template>
  <div v-if="isOpen" class="modal-overlay" @click="emit('close')">
    <div class="modal-content card-form-modal" @click.stop>
      <h3>{{ isEditing() ? '✏️ Edit Card' : '➕ New Card' }}</h3>

      <form @submit="handleSubmit">
        <!-- Create-mode: profile + deck selectors -->
        <template v-if="!isEditing()">
          <div class="form-group">
            <label>Profile</label>
            <select :value="selProfileId" @change="handleProfileSelect" :disabled="saving">
              <option value="">-- Select profile --</option>
              <option v-for="p in allProfiles" :key="p.id" :value="p.id">{{ p.name }}</option>
            </select>
          </div>

          <div v-if="selProfileId" class="form-group">
            <label>Deck</label>
            <select v-model="selDeckId" :disabled="saving">
              <option value="">-- Select deck --</option>
              <option v-for="d in availableDecks" :key="d.id" :value="d.id">
                {{ d.name }}
              </option>
            </select>
          </div>
        </template>

        <!-- Card fields -->
        <div class="form-group">
          <label>Original (Chinese) *</label>
          <input
            type="text"
            v-model="original"
            placeholder="你好世界"
            :disabled="saving"
            autofocus
          />
        </div>

        <div class="form-group">
          <label>Pinyin</label>
          <input
            type="text"
            v-model="pinyin"
            placeholder="nǐ hǎo shì jiè"
            :disabled="saving"
          />
        </div>

        <div class="form-row">
          <div class="form-group">
            <label>Language</label>
            <select v-model="targetLang" :disabled="saving">
              <option value="en">English</option>
              <option value="fr">Français</option>
            </select>
          </div>

          <div class="form-group">
            <label>Difficulty</label>
            <select v-model="difficulty" :disabled="saving">
              <option value="new">New</option>
              <option value="hard">Hard</option>
              <option value="good">Good</option>
              <option value="easy">Easy</option>
            </select>
          </div>
        </div>

        <div class="form-group">
          <label>Translation *</label>
          <input
            type="text"
            v-model="translation"
            placeholder="Hello world"
            :disabled="saving"
          />
        </div>

        <div class="form-group">
          <label>Context</label>
          <textarea
            v-model="context"
            placeholder="Usage context..."
            rows="2"
            :disabled="saving"
          />
        </div>

        <div class="form-group">
          <label>Grammar</label>
          <textarea
            v-model="grammar"
            placeholder="Grammar notes..."
            rows="2"
            :disabled="saving"
          />
        </div>

        <div class="form-group">
          <label>Example</label>
          <textarea
            v-model="example"
            placeholder="Another example sentence..."
            rows="2"
            :disabled="saving"
          />
        </div>

        <div v-if="error" class="error-message">{{ error }}</div>

        <div class="modal-actions">
          <button type="button" class="cancel-btn" @click="emit('close')" :disabled="saving">
            Cancel
          </button>
          <button type="submit" class="create-btn" :disabled="saving">
            {{ saving ? '💾 Saving...' : '💾 Save Card' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
